### ISSUE TITLE
npm那边貌似没更新，node版本一高就报错

### ISSUE THREAD

**Issue by ohcrfpv** [caolvchong/tpl#4]
如题

**Comment by caolvchong** [comment]
更新了

**Comment by ohcrfpv** [comment]
@caolvchong 👌，有折腾了一个 sublime text 的小插件，[https://packagecontrol.io/packages/Tpl](https://packagecontrol.io/packages/Tpl)，｀ctrl + alt + t｀就可以转换成js，不用每次都终端里面cd到那个文件夹，再执行命令
